Create whats_next.md
pyslackers/community pull request #9
Opened 2017-06-10 21:42 UTC by joesanford

2017-06-10 21:45 UTC, mattrasband requested changes

2017-06-10 21:45 UTC, mrasband commented on whats_next.md
> +The easiest way is always to ask questions and request code reviews in #code-review. We will try to help as much as we can and offer advice on what you are doing and how to improve. If you can you sh
Mind deep-linking to our `#help` channel? code-review is gone

2017-06-10 21:45 UTC, mrasband commented on whats_next.md
> +If you want to find a project to join, take a look at #community-projects where we run some of our own projects. You can even start your own and get some of us to join if we're interested.
Deep link please with the pep8 naming!

2017-06-11 14:58 UTC, joesanford commented
Yeah should have dropped those in when ported to MD. All updated.

2017-06-11 16:56 UTC, ovv commented
I wonder if it's not best to rename this file to something like `intermediate.md` so we could create a `beginner.md` ? Or something in this idea ?

2017-06-11 17:09 UTC, mrasband commented
Probably a good idea, maybe a python journey folder and we can put beginner/intermediate/advanced in there

2017-06-11 21:35 UTC, joesanford commented
Maybe since the document isn't too long yet, we should just split it into different sections (beginner, intermediate, etc.), with links at the top of the document to them in a table of contents?

2017-06-11 22:04 UTC, mrasband commented
Yeah, that's probably good for now until we have more content :)

2017-06-11 22:05 UTC, ovv commented
We should also make a link with the learning ressource repo. 

But we are going a bit out if scope for this PR

2017-06-16 17:28 UTC, mattrasband approved these changes

2017-06-16 17:29 UTC, merged